namespace PMB.Abb.Models.Models
{
    public enum AbbBookmaker: int
    {
        Pinnacle = 1,
        Betcity = 2,
        Sbobet = 3,
        Marathon = 4,
        _188bet = 5,
        Fonbet = 6,
        LSBet = 7,
        Baltbet = 8,
        Bwin = 9,
        Bet365 = 10,
        Betfair = 11,
        DafabetOW = 12,
        WilliamHill = 13,
        Betclic = 14,
        Zenitbet = 15,
        Tennisi = 16,
        PariMatch = 17,
        LigaStavok = 18,
        Unibet = 19,
        DafaSports = 20,
        _1xbet = 21,
        Favbet = 22,
        BetAtHome = 23,
        _10bet = 24,
        _5Dimes = 25,
        Totogaming = 26,
        Olimp = 27,
        Tipico = 29,
        Leon = 30,
        Matchbook = 31,
        Ladbrokes = 32,
        Jetbull = 33,
        Vbet = 34,
        Titanbet = 36,
        GGBet = 37,
        Betfred = 45,
        Tipbet = 47,
        Betsson = 48,
        Smarkets = 50,
        Intertops = 51,
        Boylesports = 52,
        PaddyPower = 53,
        BetOnline = 56,
        Cashpoint = 57,
        Psk = 58,
        Interwetten = 60,
        Goldenpalace = 61,
        Goalbet = 63,
        Betvictor = 65,
        Winlinebet = 71,
        Bodog = 73,
        TonyBet = 74,
        Efbet = 75,
        Betway = 78,
        BFSportsbook = 79,
        Kladise = 81,
        Novibet = 83,
        Wplay = 85,
        Cloudbet = 92,
        _888Sport = 95,
        Pokerstars = 99,
        Sportmarket = 105,
        JoyCasino = 110,
        BetinAsia = 119,
        FortuneJack = 127,
        Meridianbet = 128,
        Tempobet = 130,
        Sportsbet = 131,
        None
    }
}